### ISSUE TITLE
Warning displayed when creating a release

### ISSUE THREAD

**Issue by rissicay** [mbuhot/plug_static_index_html#2]
The warning are not causing any issues with the build, just thought i'll list them in case:

==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :credo
    :dialyxir

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

**Comment by mbuhot** [comment]
Thanks @rissicay and @tmaszk, I'll tag and release a new version to hex 👍

**Comment by mbuhot** [comment]
version 1.0.0 is now published to hex including changes from #3.
