### ISSUE TITLE
Adding index.html to all unnamed paths

### ISSUE THREAD

**Issue by micahrye** [mbuhot/plug_static_index_html#4]
I am attempting to use plug_static_index_html for a project where Phoenix is the backend and React is the front end. I want serve my React app from the root url, i.e. `localhost:4000/` and let it take care of its own routing. 

I also want to allow the React app to query endpoints such as `localhost:4000/api/data/`.  This issue is if I am using `plug_static_index_html` it will append `index.html` to any path that does not have a named file endpoint so `api/data/` becomes `api/data/index.html` and the react app is not able to access the endpoint and i get the following error on Phoenix: 
```
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /api/data/index.html (CrpWeb.Router)
```

I can get around this by changing the Phoenix router from `get "/data", APIController, :index` to `get "/data/index.html", APIController, :index` 

I was wondering if there is a way to exclude a path from having `plug_static_index_html`? Or if I am generally using this project wrong, etc? 

Thanks.

**Comment by mbuhot** [comment]
The `init` callback for the plug builds a regex that is used to match requests that end in `/`.
We could add an option to supply your own custom regex?

```
plug Plug.Static.IndexHtml, matcher: ~r[^/$] 
```

This would only match requests to `/`.
