### ISSUE TITLE
Doesn't match root path without slash

### ISSUE THREAD

**Issue by augnustin** [mbuhot/plug_static_index_html#5]
Great repo! Thanks.

I  have set:

```
  plug(
    Plug.Static.IndexHtml,
    at: "/whatever"
  )
```

It works for `/whatever/`, but not `/whatever`. Is that on purpose?

Feels like a limitation to me.

**Comment by mbuhot** [comment]
> It works for `/whatever/`, but not `/whatever`. Is that on purpose?

Yes, to determine if an arbitrary URL is a directory, we'd need to perform a directory listing then possibly cache the results. It would add a lot of complexity to this very simple library.

**Comment by augnustin** [comment]
Fine but this should be documented, shouldn't it?

**Comment by mbuhot** [comment]
PRs welcome.

Feel free to clarify the wording of "requests to paths without a filename" at  https://github.com/mbuhot/plug_static_index_html/blob/1.0.0/lib/plug_static_index_html.ex#L4
